version: '3.8'

services:
  proxys:
    image: gwangbin0607/auction_application:proxy_lastest
    build: ./proxy
    ports:
      - $HOSTPORT:$CONTAINERPORT
      - $TCPHOSTPORT:$TCPCONTAINERPORT
    depends_on:
      - http
      - tcp   

  http:
    image: gwangbin0607/auction_application:http_lastest
    build:
      context: ./Backend
      dockerfile: ./http/Dockerfile.prod
    volumes:
      - type: bind
        source: ./Backend/images
        target: /images

  tcp:
    image: gwangbin0607/auction_application:tcp_lastest
    build:
      context: ./Backend
      dockerfile: ./tcp/Dockerfile.prod
