version: '3.8'

services:
  proxys:
    image: gwangbin0607/auction_application:proxy_lastest
    build: ./proxy
    ports:
      - $HOSTPORT:$CONTAINERPORT
    depends_on:
      - backends  

  http:
    image: gwangbin0607/auction_application:http_lastest
    build:
      context: ./Backend/http
      dockerfile: Dockerfile.dev

  tcp:
    image: gwangbin0607/auction_application:tcp_lastest
    build:
      context: ./Backend/tcp
      dockerfile: Dockerfile 