version: '3.8'

services:
  proxys:
    image: gwangbin0607/auction_application:proxy_lastest
    build: ./proxy
    ports:
      - $HOSTPORT:$CONTAINERPORT
    depends_on:
      - backends  

  backends:
    image: gwangbin0607/auction_application:backend_lastest
    build: 
      context: ./Backend
      dockerfile: Dockerfile.prod      