name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: gwangbin0607
          password: '!Qq61365377'
      -
        name: checkout
        id: docker_build
        uses: actions/checkout@v3
      -
        name: Create Shell File
        run: |
          echo "hello" >> entry_test.sh
          echo export PORT=80 >> entry_test.sh
          echo 'envsubst '${PORT}' < /etc/nginx/nginx_default.conf > /etc/nginx/nginx.conf' >> entry_test.sh
          echo nginx -g 'daemon off;'
      -
        name: docker-compose build
        run: docker-compose build
      -
        name: docker-compose push
        run: docker-compose push
