name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: gwangbin0607
          password: '!Qq61365377'
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: Create Shell File
        run: |
          echo '#!/bin/bash' >> ./proxy/entry_test.sh
          echo echo "hellaao" >> ./proxy/entry_test.sh
          echo export NODEPORT=3100 >> ./proxy/entry_test.sh
          echo export PORT=$Secrete_PORT >> ./proxy/entry_test.sh
          echo 'envsubst '${PORT}' < /etc/nginx/nginx_default.conf > /etc/nginx/nginx.conf' >> ./proxy/entry_test.sh
          echo nginx -g "'daemon off;'" >> ./proxy/entry_test.sh
          cd proxy
          ls -l
        env: 
          Secrete_PORT: 80
      -
        name: docker-compose build
        run: docker-compose build
      -
        name: docker-compose push
        run: docker-compose push
  pull-run-image:
    needs: build-image
    name: continous deploy
    runs-on: ubuntu-latest
    steps:
      - 
        name: Connected ec2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-125-247-240.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          port: 22
          key: ${{secrets.REMOTE_SSH_KEY}}
          script:
            "docker-compose pull && docker-compose up -d"
      
