name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: Create Shell File
        run: |
          echo '#!/bin/bash' >> ./proxy/entry_test.sh
          echo echo "hellaao" >> ./proxy/entry_test.sh
          echo export HTTPNODEPORT=$NODEJSPORT >> ./proxy/entry_test.sh
          echo export HTTPPORT=$NGINXPORT >> ./proxy/entry_test.sh
          echo export TCPNODEPORT=$TCPNODEJSPORT >> ./proxy/entry_test.sh
          echo export TCPPORT=$TCPNGINXPORT >> ./proxy/entry_test.sh
          echo 'envsubst '\'\${HTTPPORT},\${HTTPNODEPORT},\${TCPNODEPORT},\${TCPPORT}\'' < /etc/nginx/nginx_default.conf > /etc/nginx/nginx.conf' >> ./proxy/entry_test.sh
          echo nginx -g "'daemon off;'" >> ./proxy/entry_test.sh
        env: 
          NODEJSPORT: ${{secrets.NODEJSPORT}}
          NGINXPORT: ${{secrets.NGINXPORT}}
          TCPNODEJSPORT: ${{secrets.TCPNODEJSPORT}}
          TCPNGINXPORT: ${{secrets.TCPNGINXPORT}}
      -
        name: Create .env file http
        run: |
          echo TCPPORT=$NODEJSPORT >> ./Backend/http/.env
          echo PORT=$NODEJSPORT >> ./Backend/http/.env
          echo PROD_USERNAME=$PROD_USERNAME >> ./Backend/http/.env
          echo PROD_PASSWORD=$PROD_PASSWORD >> ./Backend/http/.env
          echo PROD_DATABASE=$PROD_DATABASE >> ./Backend/http/.env
          echo PROD_HOST=$PROD_HOST >> ./Backend/http/.env
          echo PROD_PORT=$PROD_PORT >> ./Backend/http/.env
          cp ./Backend/http/.env ./Backend/tcp
        
        env:
          TCPNODEJSPORT: ${{secrets.TCPNODEJSPORT}}
          NODEJSPORT: ${{secrets.NODEJSPORT}}
          PROD_USERNAME: ${{secrets.PROD_USERNAME}}
          PROD_PASSWORD: ${{secrets.PROD_PASSWORD}}
          PROD_DATABASE: ${{secrets.PROD_DATABASE}}
          PROD_HOST: ${{secrets.PROD_HOST}}
          PROD_PORT: ${{secrets.PROD_PORT}}
      -
        name: docker-compose build
        run: docker-compose -f docker-compose.prod.yml build
        env:
          HOSTPORT: ${{secrets.HOSTPORT}}
          CONTAINERPORT: ${{secrets.CONTAINERPORT}}
          TCPHOSTPORT: ${{secrets.TCPHOSTPORT}}
          TCPCONTAINERPORT: ${{secrets.TCPCONTAINERPORT}}
      -
        name: docker-compose push
        run: docker-compose -f docker-compose.prod.yml push
        env:
          HOSTPORT: ${{secrets.HOSTPORT}}
          CONTAINERPORT: ${{secrets.CONTAINERPORT}}
          TCPHOSTPORT: ${{secrets.TCPHOSTPORT}}
          TCPCONTAINERPORT: ${{secrets.TCPCONTAINERPORT}}
  pull-run-image:
    needs: build-image
    name: continous deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      -
        name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{secrets.REMOTE_USERNAME}}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{secrets.REMOTE_PORT}}
          source: "docker-compose.prod.yml"
          target: "/home/ec2-user/"
      - 
        name: Connected to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USERNAME}}
          port: ${{secrets.REMOTE_PORT}}
          key: ${{secrets.REMOTE_SSH_KEY}}
          script:
            "export HOSTPORT=${{secrets.HOSTPORT}} && export CONTAINERPORT=${{secrets.CONTAINERPORT}} && export TCPHOSTPORT=${{secrets.TCPHOSTPORT}} && export TCPCONTAINERPORT=${{secrets.TCPCONTAINERPORT}} && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up -d --no-build --remove-orphans"
      
